### ISSUE TITLE
PrepareDatabaseNew.groovy does not create all files

### ISSUE THREAD

**Issue by marcelm** [mikessh/migmap#2]
Hi, when I run `groovy PrepareDatabaseNew.groovy` in the `dataprep/` directory, most of the time not all database files are created. The `.fa` files are there, but makeblastdb seems to not have run for some of them. It’s not deterministic. Here is an example:

```
$ groovy PrepareDatabaseNew.groovy ; ls database|wc -l
90
$ groovy PrepareDatabaseNew.groovy ; ls database|wc -l
120
$ groovy PrepareDatabaseNew.groovy ; ls database|wc -l
99
```

When I changed the `"makeblastdb ...".execute()` line in the script to `println "makeblastdb ...".execute().text`, it started working and all 126 (in my case) expected files are created.

**Comment by mikessh** [comment]
Thanks, seems like I've totally missed this when running script from IDE. Apparently some of those processes were prematurely terminated.

**Comment by marcelm** [comment]
Thanks!
