### ISSUE TITLE
Mutation nomenclature

### ISSUE THREAD

**Issue by Tatster** [mikessh/migmap#23]
Hello,
I'm having trouble relating the mutation description back to the sequence.
_eg_ S119:A>C. I take this to mean the 119th nucleotide (after concatenating the domains) has mutated from A to C. Does the **S** stand for **S**ubstitution? I also see **I** (for **I**nsertion perhaps?).
When I check these against the sequence the residues in the positions indicated don't always match up with what the mutation should have effected. Is there an explanation for this - some indicator somewhere implying the starting nucleotide index should be incremented somehow. Sometimes I can see that all the numbers are out 1 or 3 residues - but the rule isn't consistent across all my sequences.
Thanks in advance for any advice.

**Comment by mikessh** [comment]
Hi!
Yes S,I,D stand for substitution, insertion and deletion. The coordinates are 0-based and are given in respect to the start of Variable segment sequence, even if read does not reach it. You can check your reads with online [igblast](http://www.ncbi.nlm.nih.gov/igblast/igblast.cgi) and see if the shif is equal to the start of Variable segment alignment in read. Please let me know if this helps.
