### ISSUE TITLE
Preserving the headers of the FASTQ file in the output chart

### ISSUE THREAD

**Issue by RebeccaKatz** [mikessh/migmap#4]
Hi Mikhail, 
How are you? My name is Rebecca and I am a Masters student studying Bioengineering. 
I am trying to use your IgWrapper on FASTQ data that I have an was wondering if there is a way to keep the names of the sequences (the headers) in the output file. I have tried multiple things without success and was wondering if there is a built in way to do this.
Thank you

**Comment by mikessh** [comment]
Dear Rebecca,
Sorry for a very late reply (I've also got your mail). Currently there is no way to do it and it requires major re-implementation of this tool. Unfortunately, right now I'm unable to resolve this issue, but I'll keep it in mind and return to it in a week or two.

**Comment by RebeccaKatz** [comment]
Thank you for you reply! Please keep me posted

**Comment by mikessh** [comment]
@RebeccaKatz better late than never, feel free to try re-written version, binaries are [here](https://github.com/mikessh/higblast/tree/0.9.0). Instructions can be found in readme, you now need to install igblastn and makeblastdb binaries.
Example command to keep read headers will be 

``` bash
java -Xmx8G -jar higblast-0.9.0.jar --by-read -R IGH -S human sample.fastq.gz out.txt
```

**Comment by RebeccaKatz** [comment]
Thanks! I will check it out :)
