### ISSUE TITLE
--custom-database not working

### ISSUE THREAD

**Issue by darth-donut** [mikessh/migmap#43]
Hi,
As the title suggests, when specifying --custom-database my_segments.txt in migmap, it returns the following error:

![screen shot 2017-01-17 at 3 48 10 pm](https://cloud.githubusercontent.com/assets/12458705/22008344/82052b6e-dcce-11e6-8fdc-494a5264c5ae.png)

### Reproducing the error:
1) Downloaded IMGT/GENE-DB files
2) Parsed them using [imgtparser](https://github.com/antigenomics/imgtparser) - `java -jar imgtparser-1.0.0.jar -nmsb human_igh.imgt out`, lets assume human_igh.imgt is all that's required
3) `java -jar migmap-1.0.1.jar --custom-database out.txt --all-alleles --allow-incomplete --allow-noncoding --allow-no-cdr3 --allow-noncanonical --blast-dir /path/to/my/blast1.4 --data-dir /path/to/my/blast1.4_data -S human -R IGH infile.fastq out`
4) Just to make sure, I've also tried running `java -jar migmap-1.0.1.jar com.antigenomics.migmap.AnnotateSegments -S human -R IGH out.txt annotated_out.txt`, followed by (3) again but substituting **_out.txt_** with **_annotated_out.txt_** with no luck

I've also tried doing --custom-database segments.txt, the file that's provided in this repo [here](https://github.com/mikessh/migmap/blob/master/src/main/resources/segments.txt), and the same error appeared!

It would be great to see a working example (string of commands) from the raw IMGT files right down to the final segments.txt file that can be used for `--custom-database`.

Cheers,
Harry

**Comment by jfong361** [comment]
Looking at [this line of code](https://github.com/mikessh/migmap/blob/bc5c00d402a17fc023d57ce6a55ec925f2cdf558/src/main/groovy/com/antigenomics/migmap/genomic/SegmentDatabase.groovy#L56), I believe 
```groovy
new File(segmentsFilePath)
```
should be
```groovy
new FileInputStream(segmentsFilePath)
````
instead?
