### ISSUE TITLE
MiGMAP and MiXCR

### ISSUE THREAD

**Issue by suntaosimon** [mikessh/migmap#45]
I have read the paper "High-quality full-length immunoglobulin profiling with unique molecular barcoding" and noticed this awesome software. Just want to know what the specific feature of MiGMAP compared with MiXCR? Because our lab is currently only using MiXCR for the TCR data analysis.
Thanks!

**Comment by mikessh** [comment]
MIGMAP is a wrapper of IgBlast software:

* Its based on IgBlast so it uses a different alignment algorithm
* It has a different output format for hypermutations
* Apache license (free/no restrictions)

For TCR analysis with amplicon sequencing data almost all tools starting from mitcr generally perform well in terms of accuracy

**Comment by suntaosimon** [comment]
Sounds cool! Thanks!
