### ISSUE TITLE
Command line issues

### ISSUE THREAD

**Issue by colindaven** [mikessh/migmap#48]
Hi,

I have tried Miniconda and the git clone versions and have got nowhere so far.

Java: java8 openjdk version "1.8.0_102"

```
java -Xmx8g  -jar /mnt/ngsnfs/tools/miniconda2/share/migmap.jar  -R IGH --data-dir /mnt/ngsnfs/tools/migmap/migmap/data/internal_data/ -S human in.fa
```

```
Also no luck
java -Xmx8g  -jar /mnt/ngsnfs/tools/miniconda2/share/migmap.jar  -R IGH --data-dir /mnt/ngsnfs/tools/migmap/migmap/data/ -S human in.fa
```

Any ideas? Any way to provoke a helpful debug msg instead of just the usage ?
usage: migmap [options] input.(fa/fastq)[.gz] (output_file/- for stdout)
    --all-alleles                       Will use all alleles during

I presume the data files are not being found or similar. igblastn and makeblastdb are in the path.

Thanks,
Colin

**Comment by colindaven** [comment]
Reading further issues, I may have solved it - the out.csv is required

`java -Xmx8g -jar /mnt/ngsnfs/tools/miniconda2/share/migmap.jar -R IGH --data-dir /mnt/ngsnfs/tools/migmap/migmap/data/ -S human in.fa out.csv`

**Comment by mikessh** [comment]
Yes, if an argument is missing the usage will be displayed

**Comment by colindaven** [comment]
At the same time, the usage could be a little clearer. It looked to me for a while that the output file is optional, as it is in brackets. Perhaps required parameters - input and output files - could be listed first in the usage ?

usage: migmap [options] input.(fa/fastq)[.gz] (output_file/- for stdout)
